#!/usr/bin/env bash

# In this file:
#                 - minor modifications to some GNU tools


alias la="ls -a"
alias ll="ls -l"
alias l="ls"

alias nano="nano --guidestripe 80 --emptyline --linenumbers -s aspell --nohelp"
