#!/usr/bin/env bash


# In this file:
#                  - utility bash functions


# Create a local directory and change into it.
function mkd
{
    mkdir "$1"
    cd "$1" || return 1
}


# Discard the current directory if empty.
function rmd
{
    cd ..
    rmdir "$OLDPWD"
}


# Execute a program and don't care about parent shell or output.
function run
{
    nohup "$@" >/dev/null &
}


# Start a program into an X server on the current VT.
function run-gui
{
    let _DISPLAY=$XDG_VTNR-1
    xinit -geometry =1920x1080+0+0 "$@" -- :$_DISPLAY vt$XDG_VTNR
}


# Look everywhere.
function myfind
{
    find / -name "$1" 2>/dev/null
}


# Intended to be ran as root.
function net
{
    # Constants.
    local IFACE=wlo1
    local FNAME="$1.conf"

    # All login credentials are stored here.
    cd /etc/wpa_supplicant/ || return 1

    # The symbolic link 'conf' points to the chosen network.
    rm -f conf
    if [ ! -f "$FNAME" ]; then echo 'No such network'; return 2; fi
    ln -s "$FNAME" conf

    # Authenticate.
    killall wpa_supplicant dhclient 2>/dev/null
    wpa_supplicant -c $FNAME -i $IFACE -B || return 3
    dhclient $IFACE  || return 4
    watch ip a
}


# Tar a directory.
# Drop last character if it's '/'.
function compress
{
    NAME="$1"
    if [[ "${NAME: -1}" == '/' ]]; then
        NAME="${NAME::-1}"
    fi
    TARNAME="$NAME".tar.gz

    tar czf "$TARNAME" "$NAME"

    du -h "$TARNAME"
}
