#!/usr/bin/env bash


# Start an X server, X client and one graphical applkucation on the current VT.


if [[ $# < 1 ]]; then
    echo "Please specify a program to launch under X."
    exit 1
fi


let _DISPLAY=$XDG_VTNR-1
xinit -geometry =1920x1080+0+0 $* -- :$_DISPLAY vt$XDG_VTNR
